#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ORDesignerWalktrough
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="baan4db")]
	public partial class Baan4DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definitionen der Erweiterungsmethoden
    partial void OnCreated();
    partial void Insertttccom020100(ttccom020100 instance);
    partial void Updatettccom020100(ttccom020100 instance);
    partial void Deletettccom020100(ttccom020100 instance);
    partial void Insertttdpur040100(ttdpur040100 instance);
    partial void Updatettdpur040100(ttdpur040100 instance);
    partial void Deletettdpur040100(ttdpur040100 instance);
    #endregion
		
		public Baan4DataContext() : 
				base(global::ORDesignerWalktrough.Properties.Settings.Default.baan4dbConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public Baan4DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public Baan4DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public Baan4DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public Baan4DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<ttccom020100> ttccom020100
		{
			get
			{
				return this.GetTable<ttccom020100>();
			}
		}
		
		public System.Data.Linq.Table<ttdpur040100> ttdpur040100
		{
			get
			{
				return this.GetTable<ttdpur040100>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ttccom020100")]
	public partial class ttccom020100 : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _t_suno;
		
		private string _t_ctit;
		
		private string _t_nama;
		
		private string _t_namb;
		
		private string _t_namc;
		
		private string _t_namd;
		
		private string _t_name;
		
		private string _t_namf;
		
		private string _t_pstc;
		
		private short _t_comp;
		
		private string _t_creg;
		
		private string _t_pspr;
		
		private string _t_pstx;
		
		private byte _t_sndr;
		
		private string _t_ccor;
		
		private string _t_cwar;
		
		private string _t_refa;
		
		private string _t_refs;
		
		private string _t_ocus;
		
		private string _t_telp;
		
		private string _t_telx;
		
		private string _t_tefx;
		
		private string _t_seak;
		
		private string _t_cbrn;
		
		private string _t_cban;
		
		private string _t_cfcc;
		
		private string _t_fano;
		
		private int _t_ccon;
		
		private string _t_cpay;
		
		private string _t_ccrs;
		
		private string _t_cdec;
		
		private string _t_ccty;
		
		private string _t_clan;
		
		private string _t_ccur;
		
		private byte _t_cvyn;
		
		private string _t_scus;
		
		private string _t_cplp;
		
		private string _t_cfsg;
		
		private string _t_paym;
		
		private string _t_cuno;
		
		private byte _t_qual;
		
		private double _t_buor;
		
		private double _t_buin;
		
		private float _t_odis;
		
		private byte _t_subc;
		
		private short _t_cryr;
		
		private double _t_tovr_1;
		
		private double _t_tovr_2;
		
		private double _t_tovr_3;
		
		private double _t_tovr_4;
		
		private double _t_tovr_5;
		
		private byte _t_sust;
		
		private short _t_eded;
		
		private string _t_cadr;
		
		private string _t_fovn;
		
		private byte _t_inrl;
		
		private short _t_iscn;
		
		private string _t_cotp;
		
		private int _t_txta;
		
		private string _t_geoc_l;
		
		private byte _t_scon_c;
		
		private byte _t_rcon_c;
		
		private int _t_dld1_c;
		
		private int _t_dld2_c;
		
		private int _t_Refcntd;
		
		private int _t_Refcntu;
		
    #region Definitionen der Erweiterungsmethoden
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Ont_sunoChanging(string value);
    partial void Ont_sunoChanged();
    partial void Ont_ctitChanging(string value);
    partial void Ont_ctitChanged();
    partial void Ont_namaChanging(string value);
    partial void Ont_namaChanged();
    partial void Ont_nambChanging(string value);
    partial void Ont_nambChanged();
    partial void Ont_namcChanging(string value);
    partial void Ont_namcChanged();
    partial void Ont_namdChanging(string value);
    partial void Ont_namdChanged();
    partial void Ont_nameChanging(string value);
    partial void Ont_nameChanged();
    partial void Ont_namfChanging(string value);
    partial void Ont_namfChanged();
    partial void Ont_pstcChanging(string value);
    partial void Ont_pstcChanged();
    partial void Ont_compChanging(short value);
    partial void Ont_compChanged();
    partial void Ont_cregChanging(string value);
    partial void Ont_cregChanged();
    partial void Ont_psprChanging(string value);
    partial void Ont_psprChanged();
    partial void Ont_pstxChanging(string value);
    partial void Ont_pstxChanged();
    partial void Ont_sndrChanging(byte value);
    partial void Ont_sndrChanged();
    partial void Ont_ccorChanging(string value);
    partial void Ont_ccorChanged();
    partial void Ont_cwarChanging(string value);
    partial void Ont_cwarChanged();
    partial void Ont_refaChanging(string value);
    partial void Ont_refaChanged();
    partial void Ont_refsChanging(string value);
    partial void Ont_refsChanged();
    partial void Ont_ocusChanging(string value);
    partial void Ont_ocusChanged();
    partial void Ont_telpChanging(string value);
    partial void Ont_telpChanged();
    partial void Ont_telxChanging(string value);
    partial void Ont_telxChanged();
    partial void Ont_tefxChanging(string value);
    partial void Ont_tefxChanged();
    partial void Ont_seakChanging(string value);
    partial void Ont_seakChanged();
    partial void Ont_cbrnChanging(string value);
    partial void Ont_cbrnChanged();
    partial void Ont_cbanChanging(string value);
    partial void Ont_cbanChanged();
    partial void Ont_cfccChanging(string value);
    partial void Ont_cfccChanged();
    partial void Ont_fanoChanging(string value);
    partial void Ont_fanoChanged();
    partial void Ont_cconChanging(int value);
    partial void Ont_cconChanged();
    partial void Ont_cpayChanging(string value);
    partial void Ont_cpayChanged();
    partial void Ont_ccrsChanging(string value);
    partial void Ont_ccrsChanged();
    partial void Ont_cdecChanging(string value);
    partial void Ont_cdecChanged();
    partial void Ont_cctyChanging(string value);
    partial void Ont_cctyChanged();
    partial void Ont_clanChanging(string value);
    partial void Ont_clanChanged();
    partial void Ont_ccurChanging(string value);
    partial void Ont_ccurChanged();
    partial void Ont_cvynChanging(byte value);
    partial void Ont_cvynChanged();
    partial void Ont_scusChanging(string value);
    partial void Ont_scusChanged();
    partial void Ont_cplpChanging(string value);
    partial void Ont_cplpChanged();
    partial void Ont_cfsgChanging(string value);
    partial void Ont_cfsgChanged();
    partial void Ont_paymChanging(string value);
    partial void Ont_paymChanged();
    partial void Ont_cunoChanging(string value);
    partial void Ont_cunoChanged();
    partial void Ont_qualChanging(byte value);
    partial void Ont_qualChanged();
    partial void Ont_buorChanging(double value);
    partial void Ont_buorChanged();
    partial void Ont_buinChanging(double value);
    partial void Ont_buinChanged();
    partial void Ont_odisChanging(float value);
    partial void Ont_odisChanged();
    partial void Ont_subcChanging(byte value);
    partial void Ont_subcChanged();
    partial void Ont_cryrChanging(short value);
    partial void Ont_cryrChanged();
    partial void Ont_tovr_1Changing(double value);
    partial void Ont_tovr_1Changed();
    partial void Ont_tovr_2Changing(double value);
    partial void Ont_tovr_2Changed();
    partial void Ont_tovr_3Changing(double value);
    partial void Ont_tovr_3Changed();
    partial void Ont_tovr_4Changing(double value);
    partial void Ont_tovr_4Changed();
    partial void Ont_tovr_5Changing(double value);
    partial void Ont_tovr_5Changed();
    partial void Ont_sustChanging(byte value);
    partial void Ont_sustChanged();
    partial void Ont_ededChanging(short value);
    partial void Ont_ededChanged();
    partial void Ont_cadrChanging(string value);
    partial void Ont_cadrChanged();
    partial void Ont_fovnChanging(string value);
    partial void Ont_fovnChanged();
    partial void Ont_inrlChanging(byte value);
    partial void Ont_inrlChanged();
    partial void Ont_iscnChanging(short value);
    partial void Ont_iscnChanged();
    partial void Ont_cotpChanging(string value);
    partial void Ont_cotpChanged();
    partial void Ont_txtaChanging(int value);
    partial void Ont_txtaChanged();
    partial void Ont_geoc_lChanging(string value);
    partial void Ont_geoc_lChanged();
    partial void Ont_scon_cChanging(byte value);
    partial void Ont_scon_cChanged();
    partial void Ont_rcon_cChanging(byte value);
    partial void Ont_rcon_cChanged();
    partial void Ont_dld1_cChanging(int value);
    partial void Ont_dld1_cChanged();
    partial void Ont_dld2_cChanging(int value);
    partial void Ont_dld2_cChanged();
    partial void Ont_RefcntdChanging(int value);
    partial void Ont_RefcntdChanged();
    partial void Ont_RefcntuChanging(int value);
    partial void Ont_RefcntuChanged();
    #endregion
		
		public ttccom020100()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_t_suno", DbType="VarChar(6) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string t_suno
		{
			get
			{
				return this._t_suno;
			}
			set
			{
				if ((this._t_suno != value))
				{
					this.Ont_sunoChanging(value);
					this.SendPropertyChanging();
					this._t_suno = value;
					this.SendPropertyChanged("t_suno");
					this.Ont_sunoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_t_ctit", DbType="VarChar(3) NOT NULL", CanBeNull=false)]
		public string t_ctit
		{
			get
			{
				return this._t_ctit;
			}
			set
			{
				if ((this._t_ctit != value))
				{
					this.Ont_ctitChanging(value);
					this.SendPropertyChanging();
					this._t_ctit = value;
					this.SendPropertyChanged("t_ctit");
					this.Ont_ctitChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_t_nama", DbType="VarChar(35) NOT NULL", CanBeNull=false)]
		public string t_nama
		{
			get
			{
				return this._t_nama;
			}
			set
			{
				if ((this._t_nama != value))
				{
					this.Ont_namaChanging(value);
					this.SendPropertyChanging();
					this._t_nama = value;
					this.SendPropertyChanged("t_nama");
					this.Ont_namaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_t_namb", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string t_namb
		{
			get
			{
				return this._t_namb;
			}
			set
			{
				if ((this._t_namb != value))
				{
					this.Ont_nambChanging(value);
					this.SendPropertyChanging();
					this._t_namb = value;
					this.SendPropertyChanged("t_namb");
					this.Ont_nambChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_t_namc", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string t_namc
		{
			get
			{
				return this._t_namc;
			}
			set
			{
				if ((this._t_namc != value))
				{
					this.Ont_namcChanging(value);
					this.SendPropertyChanging();
					this._t_namc = value;
					this.SendPropertyChanged("t_namc");
					this.Ont_namcChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_t_namd", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string t_namd
		{
			get
			{
				return this._t_namd;
			}
			set
			{
				if ((this._t_namd != value))
				{
					this.Ont_namdChanging(value);
					this.SendPropertyChanging();
					this._t_namd = value;
					this.SendPropertyChanged("t_namd");
					this.Ont_namdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_t_name", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string t_name
		{
			get
			{
				return this._t_name;
			}
			set
			{
				if ((this._t_name != value))
				{
					this.Ont_nameChanging(value);
					this.SendPropertyChanging();
					this._t_name = value;
					this.SendPropertyChanged("t_name");
					this.Ont_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_t_namf", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string t_namf
		{
			get
			{
				return this._t_namf;
			}
			set
			{
				if ((this._t_namf != value))
				{
					this.Ont_namfChanging(value);
					this.SendPropertyChanging();
					this._t_namf = value;
					this.SendPropertyChanged("t_namf");
					this.Ont_namfChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_t_pstc", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string t_pstc
		{
			get
			{
				return this._t_pstc;
			}
			set
			{
				if ((this._t_pstc != value))
				{
					this.Ont_pstcChanging(value);
					this.SendPropertyChanging();
					this._t_pstc = value;
					this.SendPropertyChanged("t_pstc");
					this.Ont_pstcChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_t_comp", DbType="SmallInt NOT NULL")]
		public short t_comp
		{
			get
			{
				return this._t_comp;
			}
			set
			{
				if ((this._t_comp != value))
				{
					this.Ont_compChanging(value);
					this.SendPropertyChanging();
					this._t_comp = value;
					this.SendPropertyChanged("t_comp");
					this.Ont_compChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_t_creg", DbType="VarChar(3) NOT NULL", CanBeNull=false)]
		public string t_creg
		{
			get
			{
				return this._t_creg;
			}
			set
			{
				if ((this._t_creg != value))
				{
					this.Ont_cregChanging(value);
					this.SendPropertyChanging();
					this._t_creg = value;
					this.SendPropertyChanged("t_creg");
					this.Ont_cregChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_t_pspr", DbType="VarChar(6) NOT NULL", CanBeNull=false)]
		public string t_pspr
		{
			get
			{
				return this._t_pspr;
			}
			set
			{
				if ((this._t_pspr != value))
				{
					this.Ont_psprChanging(value);
					this.SendPropertyChanging();
					this._t_pspr = value;
					this.SendPropertyChanged("t_pspr");
					this.Ont_psprChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_t_pstx", DbType="VarChar(6) NOT NULL", CanBeNull=false)]
		public string t_pstx
		{
			get
			{
				return this._t_pstx;
			}
			set
			{
				if ((this._t_pstx != value))
				{
					this.Ont_pstxChanging(value);
					this.SendPropertyChanging();
					this._t_pstx = value;
					this.SendPropertyChanged("t_pstx");
					this.Ont_pstxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_t_sndr", DbType="TinyInt NOT NULL")]
		public byte t_sndr
		{
			get
			{
				return this._t_sndr;
			}
			set
			{
				if ((this._t_sndr != value))
				{
					this.Ont_sndrChanging(value);
					this.SendPropertyChanging();
					this._t_sndr = value;
					this.SendPropertyChanged("t_sndr");
					this.Ont_sndrChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_t_ccor", DbType="VarChar(3) NOT NULL", CanBeNull=false)]
		public string t_ccor
		{
			get
			{
				return this._t_ccor;
			}
			set
			{
				if ((this._t_ccor != value))
				{
					this.Ont_ccorChanging(value);
					this.SendPropertyChanging();
					this._t_ccor = value;
					this.SendPropertyChanged("t_ccor");
					this.Ont_ccorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_t_cwar", DbType="VarChar(3) NOT NULL", CanBeNull=false)]
		public string t_cwar
		{
			get
			{
				return this._t_cwar;
			}
			set
			{
				if ((this._t_cwar != value))
				{
					this.Ont_cwarChanging(value);
					this.SendPropertyChanging();
					this._t_cwar = value;
					this.SendPropertyChanged("t_cwar");
					this.Ont_cwarChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_t_refa", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string t_refa
		{
			get
			{
				return this._t_refa;
			}
			set
			{
				if ((this._t_refa != value))
				{
					this.Ont_refaChanging(value);
					this.SendPropertyChanging();
					this._t_refa = value;
					this.SendPropertyChanged("t_refa");
					this.Ont_refaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_t_refs", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string t_refs
		{
			get
			{
				return this._t_refs;
			}
			set
			{
				if ((this._t_refs != value))
				{
					this.Ont_refsChanging(value);
					this.SendPropertyChanging();
					this._t_refs = value;
					this.SendPropertyChanged("t_refs");
					this.Ont_refsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_t_ocus", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string t_ocus
		{
			get
			{
				return this._t_ocus;
			}
			set
			{
				if ((this._t_ocus != value))
				{
					this.Ont_ocusChanging(value);
					this.SendPropertyChanging();
					this._t_ocus = value;
					this.SendPropertyChanged("t_ocus");
					this.Ont_ocusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_t_telp", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string t_telp
		{
			get
			{
				return this._t_telp;
			}
			set
			{
				if ((this._t_telp != value))
				{
					this.Ont_telpChanging(value);
					this.SendPropertyChanging();
					this._t_telp = value;
					this.SendPropertyChanged("t_telp");
					this.Ont_telpChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_t_telx", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string t_telx
		{
			get
			{
				return this._t_telx;
			}
			set
			{
				if ((this._t_telx != value))
				{
					this.Ont_telxChanging(value);
					this.SendPropertyChanging();
					this._t_telx = value;
					this.SendPropertyChanged("t_telx");
					this.Ont_telxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_t_tefx", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string t_tefx
		{
			get
			{
				return this._t_tefx;
			}
			set
			{
				if ((this._t_tefx != value))
				{
					this.Ont_tefxChanging(value);
					this.SendPropertyChanging();
					this._t_tefx = value;
					this.SendPropertyChanged("t_tefx");
					this.Ont_tefxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_t_seak", DbType="VarChar(16) NOT NULL", CanBeNull=false)]
		public string t_seak
		{
			get
			{
				return this._t_seak;
			}
			set
			{
				if ((this._t_seak != value))
				{
					this.Ont_seakChanging(value);
					this.SendPropertyChanging();
					this._t_seak = value;
					this.SendPropertyChanged("t_seak");
					this.Ont_seakChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_t_cbrn", DbType="VarChar(6) NOT NULL", CanBeNull=false)]
		public string t_cbrn
		{
			get
			{
				return this._t_cbrn;
			}
			set
			{
				if ((this._t_cbrn != value))
				{
					this.Ont_cbrnChanging(value);
					this.SendPropertyChanging();
					this._t_cbrn = value;
					this.SendPropertyChanged("t_cbrn");
					this.Ont_cbrnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_t_cban", DbType="VarChar(3) NOT NULL", CanBeNull=false)]
		public string t_cban
		{
			get
			{
				return this._t_cban;
			}
			set
			{
				if ((this._t_cban != value))
				{
					this.Ont_cbanChanging(value);
					this.SendPropertyChanging();
					this._t_cban = value;
					this.SendPropertyChanged("t_cban");
					this.Ont_cbanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_t_cfcc", DbType="VarChar(3) NOT NULL", CanBeNull=false)]
		public string t_cfcc
		{
			get
			{
				return this._t_cfcc;
			}
			set
			{
				if ((this._t_cfcc != value))
				{
					this.Ont_cfccChanging(value);
					this.SendPropertyChanging();
					this._t_cfcc = value;
					this.SendPropertyChanged("t_cfcc");
					this.Ont_cfccChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_t_fano", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string t_fano
		{
			get
			{
				return this._t_fano;
			}
			set
			{
				if ((this._t_fano != value))
				{
					this.Ont_fanoChanging(value);
					this.SendPropertyChanging();
					this._t_fano = value;
					this.SendPropertyChanged("t_fano");
					this.Ont_fanoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_t_ccon", DbType="Int NOT NULL")]
		public int t_ccon
		{
			get
			{
				return this._t_ccon;
			}
			set
			{
				if ((this._t_ccon != value))
				{
					this.Ont_cconChanging(value);
					this.SendPropertyChanging();
					this._t_ccon = value;
					this.SendPropertyChanged("t_ccon");
					this.Ont_cconChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_t_cpay", DbType="VarChar(3) NOT NULL", CanBeNull=false)]
		public string t_cpay
		{
			get
			{
				return this._t_cpay;
			}
			set
			{
				if ((this._t_cpay != value))
				{
					this.Ont_cpayChanging(value);
					this.SendPropertyChanging();
					this._t_cpay = value;
					this.SendPropertyChanged("t_cpay");
					this.Ont_cpayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_t_ccrs", DbType="VarChar(3) NOT NULL", CanBeNull=false)]
		public string t_ccrs
		{
			get
			{
				return this._t_ccrs;
			}
			set
			{
				if ((this._t_ccrs != value))
				{
					this.Ont_ccrsChanging(value);
					this.SendPropertyChanging();
					this._t_ccrs = value;
					this.SendPropertyChanged("t_ccrs");
					this.Ont_ccrsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_t_cdec", DbType="VarChar(3) NOT NULL", CanBeNull=false)]
		public string t_cdec
		{
			get
			{
				return this._t_cdec;
			}
			set
			{
				if ((this._t_cdec != value))
				{
					this.Ont_cdecChanging(value);
					this.SendPropertyChanging();
					this._t_cdec = value;
					this.SendPropertyChanged("t_cdec");
					this.Ont_cdecChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_t_ccty", DbType="VarChar(3) NOT NULL", CanBeNull=false)]
		public string t_ccty
		{
			get
			{
				return this._t_ccty;
			}
			set
			{
				if ((this._t_ccty != value))
				{
					this.Ont_cctyChanging(value);
					this.SendPropertyChanging();
					this._t_ccty = value;
					this.SendPropertyChanged("t_ccty");
					this.Ont_cctyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_t_clan", DbType="VarChar(3) NOT NULL", CanBeNull=false)]
		public string t_clan
		{
			get
			{
				return this._t_clan;
			}
			set
			{
				if ((this._t_clan != value))
				{
					this.Ont_clanChanging(value);
					this.SendPropertyChanging();
					this._t_clan = value;
					this.SendPropertyChanged("t_clan");
					this.Ont_clanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_t_ccur", DbType="VarChar(3) NOT NULL", CanBeNull=false)]
		public string t_ccur
		{
			get
			{
				return this._t_ccur;
			}
			set
			{
				if ((this._t_ccur != value))
				{
					this.Ont_ccurChanging(value);
					this.SendPropertyChanging();
					this._t_ccur = value;
					this.SendPropertyChanged("t_ccur");
					this.Ont_ccurChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_t_cvyn", DbType="TinyInt NOT NULL")]
		public byte t_cvyn
		{
			get
			{
				return this._t_cvyn;
			}
			set
			{
				if ((this._t_cvyn != value))
				{
					this.Ont_cvynChanging(value);
					this.SendPropertyChanging();
					this._t_cvyn = value;
					this.SendPropertyChanged("t_cvyn");
					this.Ont_cvynChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_t_scus", DbType="VarChar(6) NOT NULL", CanBeNull=false)]
		public string t_scus
		{
			get
			{
				return this._t_scus;
			}
			set
			{
				if ((this._t_scus != value))
				{
					this.Ont_scusChanging(value);
					this.SendPropertyChanging();
					this._t_scus = value;
					this.SendPropertyChanged("t_scus");
					this.Ont_scusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_t_cplp", DbType="VarChar(3) NOT NULL", CanBeNull=false)]
		public string t_cplp
		{
			get
			{
				return this._t_cplp;
			}
			set
			{
				if ((this._t_cplp != value))
				{
					this.Ont_cplpChanging(value);
					this.SendPropertyChanging();
					this._t_cplp = value;
					this.SendPropertyChanged("t_cplp");
					this.Ont_cplpChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_t_cfsg", DbType="VarChar(3) NOT NULL", CanBeNull=false)]
		public string t_cfsg
		{
			get
			{
				return this._t_cfsg;
			}
			set
			{
				if ((this._t_cfsg != value))
				{
					this.Ont_cfsgChanging(value);
					this.SendPropertyChanging();
					this._t_cfsg = value;
					this.SendPropertyChanged("t_cfsg");
					this.Ont_cfsgChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_t_paym", DbType="VarChar(3) NOT NULL", CanBeNull=false)]
		public string t_paym
		{
			get
			{
				return this._t_paym;
			}
			set
			{
				if ((this._t_paym != value))
				{
					this.Ont_paymChanging(value);
					this.SendPropertyChanging();
					this._t_paym = value;
					this.SendPropertyChanged("t_paym");
					this.Ont_paymChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_t_cuno", DbType="VarChar(6) NOT NULL", CanBeNull=false)]
		public string t_cuno
		{
			get
			{
				return this._t_cuno;
			}
			set
			{
				if ((this._t_cuno != value))
				{
					this.Ont_cunoChanging(value);
					this.SendPropertyChanging();
					this._t_cuno = value;
					this.SendPropertyChanged("t_cuno");
					this.Ont_cunoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_t_qual", DbType="TinyInt NOT NULL")]
		public byte t_qual
		{
			get
			{
				return this._t_qual;
			}
			set
			{
				if ((this._t_qual != value))
				{
					this.Ont_qualChanging(value);
					this.SendPropertyChanging();
					this._t_qual = value;
					this.SendPropertyChanged("t_qual");
					this.Ont_qualChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_t_buor", DbType="Float NOT NULL")]
		public double t_buor
		{
			get
			{
				return this._t_buor;
			}
			set
			{
				if ((this._t_buor != value))
				{
					this.Ont_buorChanging(value);
					this.SendPropertyChanging();
					this._t_buor = value;
					this.SendPropertyChanged("t_buor");
					this.Ont_buorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_t_buin", DbType="Float NOT NULL")]
		public double t_buin
		{
			get
			{
				return this._t_buin;
			}
			set
			{
				if ((this._t_buin != value))
				{
					this.Ont_buinChanging(value);
					this.SendPropertyChanging();
					this._t_buin = value;
					this.SendPropertyChanged("t_buin");
					this.Ont_buinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_t_odis", DbType="Real NOT NULL")]
		public float t_odis
		{
			get
			{
				return this._t_odis;
			}
			set
			{
				if ((this._t_odis != value))
				{
					this.Ont_odisChanging(value);
					this.SendPropertyChanging();
					this._t_odis = value;
					this.SendPropertyChanged("t_odis");
					this.Ont_odisChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_t_subc", DbType="TinyInt NOT NULL")]
		public byte t_subc
		{
			get
			{
				return this._t_subc;
			}
			set
			{
				if ((this._t_subc != value))
				{
					this.Ont_subcChanging(value);
					this.SendPropertyChanging();
					this._t_subc = value;
					this.SendPropertyChanged("t_subc");
					this.Ont_subcChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_t_cryr", DbType="SmallInt NOT NULL")]
		public short t_cryr
		{
			get
			{
				return this._t_cryr;
			}
			set
			{
				if ((this._t_cryr != value))
				{
					this.Ont_cryrChanging(value);
					this.SendPropertyChanging();
					this._t_cryr = value;
					this.SendPropertyChanged("t_cryr");
					this.Ont_cryrChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_t_tovr_1", DbType="Float NOT NULL")]
		public double t_tovr_1
		{
			get
			{
				return this._t_tovr_1;
			}
			set
			{
				if ((this._t_tovr_1 != value))
				{
					this.Ont_tovr_1Changing(value);
					this.SendPropertyChanging();
					this._t_tovr_1 = value;
					this.SendPropertyChanged("t_tovr_1");
					this.Ont_tovr_1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_t_tovr_2", DbType="Float NOT NULL")]
		public double t_tovr_2
		{
			get
			{
				return this._t_tovr_2;
			}
			set
			{
				if ((this._t_tovr_2 != value))
				{
					this.Ont_tovr_2Changing(value);
					this.SendPropertyChanging();
					this._t_tovr_2 = value;
					this.SendPropertyChanged("t_tovr_2");
					this.Ont_tovr_2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_t_tovr_3", DbType="Float NOT NULL")]
		public double t_tovr_3
		{
			get
			{
				return this._t_tovr_3;
			}
			set
			{
				if ((this._t_tovr_3 != value))
				{
					this.Ont_tovr_3Changing(value);
					this.SendPropertyChanging();
					this._t_tovr_3 = value;
					this.SendPropertyChanged("t_tovr_3");
					this.Ont_tovr_3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_t_tovr_4", DbType="Float NOT NULL")]
		public double t_tovr_4
		{
			get
			{
				return this._t_tovr_4;
			}
			set
			{
				if ((this._t_tovr_4 != value))
				{
					this.Ont_tovr_4Changing(value);
					this.SendPropertyChanging();
					this._t_tovr_4 = value;
					this.SendPropertyChanged("t_tovr_4");
					this.Ont_tovr_4Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_t_tovr_5", DbType="Float NOT NULL")]
		public double t_tovr_5
		{
			get
			{
				return this._t_tovr_5;
			}
			set
			{
				if ((this._t_tovr_5 != value))
				{
					this.Ont_tovr_5Changing(value);
					this.SendPropertyChanging();
					this._t_tovr_5 = value;
					this.SendPropertyChanged("t_tovr_5");
					this.Ont_tovr_5Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_t_sust", DbType="TinyInt NOT NULL")]
		public byte t_sust
		{
			get
			{
				return this._t_sust;
			}
			set
			{
				if ((this._t_sust != value))
				{
					this.Ont_sustChanging(value);
					this.SendPropertyChanging();
					this._t_sust = value;
					this.SendPropertyChanged("t_sust");
					this.Ont_sustChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_t_eded", DbType="SmallInt NOT NULL")]
		public short t_eded
		{
			get
			{
				return this._t_eded;
			}
			set
			{
				if ((this._t_eded != value))
				{
					this.Ont_ededChanging(value);
					this.SendPropertyChanging();
					this._t_eded = value;
					this.SendPropertyChanged("t_eded");
					this.Ont_ededChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_t_cadr", DbType="VarChar(6) NOT NULL", CanBeNull=false)]
		public string t_cadr
		{
			get
			{
				return this._t_cadr;
			}
			set
			{
				if ((this._t_cadr != value))
				{
					this.Ont_cadrChanging(value);
					this.SendPropertyChanging();
					this._t_cadr = value;
					this.SendPropertyChanged("t_cadr");
					this.Ont_cadrChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_t_fovn", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string t_fovn
		{
			get
			{
				return this._t_fovn;
			}
			set
			{
				if ((this._t_fovn != value))
				{
					this.Ont_fovnChanging(value);
					this.SendPropertyChanging();
					this._t_fovn = value;
					this.SendPropertyChanged("t_fovn");
					this.Ont_fovnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_t_inrl", DbType="TinyInt NOT NULL")]
		public byte t_inrl
		{
			get
			{
				return this._t_inrl;
			}
			set
			{
				if ((this._t_inrl != value))
				{
					this.Ont_inrlChanging(value);
					this.SendPropertyChanging();
					this._t_inrl = value;
					this.SendPropertyChanged("t_inrl");
					this.Ont_inrlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_t_iscn", DbType="SmallInt NOT NULL")]
		public short t_iscn
		{
			get
			{
				return this._t_iscn;
			}
			set
			{
				if ((this._t_iscn != value))
				{
					this.Ont_iscnChanging(value);
					this.SendPropertyChanging();
					this._t_iscn = value;
					this.SendPropertyChanged("t_iscn");
					this.Ont_iscnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_t_cotp", DbType="VarChar(3) NOT NULL", CanBeNull=false)]
		public string t_cotp
		{
			get
			{
				return this._t_cotp;
			}
			set
			{
				if ((this._t_cotp != value))
				{
					this.Ont_cotpChanging(value);
					this.SendPropertyChanging();
					this._t_cotp = value;
					this.SendPropertyChanged("t_cotp");
					this.Ont_cotpChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_t_txta", DbType="Int NOT NULL")]
		public int t_txta
		{
			get
			{
				return this._t_txta;
			}
			set
			{
				if ((this._t_txta != value))
				{
					this.Ont_txtaChanging(value);
					this.SendPropertyChanging();
					this._t_txta = value;
					this.SendPropertyChanged("t_txta");
					this.Ont_txtaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_t_geoc_l", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string t_geoc_l
		{
			get
			{
				return this._t_geoc_l;
			}
			set
			{
				if ((this._t_geoc_l != value))
				{
					this.Ont_geoc_lChanging(value);
					this.SendPropertyChanging();
					this._t_geoc_l = value;
					this.SendPropertyChanged("t_geoc_l");
					this.Ont_geoc_lChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_t_scon_c", DbType="TinyInt NOT NULL")]
		public byte t_scon_c
		{
			get
			{
				return this._t_scon_c;
			}
			set
			{
				if ((this._t_scon_c != value))
				{
					this.Ont_scon_cChanging(value);
					this.SendPropertyChanging();
					this._t_scon_c = value;
					this.SendPropertyChanged("t_scon_c");
					this.Ont_scon_cChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_t_rcon_c", DbType="TinyInt NOT NULL")]
		public byte t_rcon_c
		{
			get
			{
				return this._t_rcon_c;
			}
			set
			{
				if ((this._t_rcon_c != value))
				{
					this.Ont_rcon_cChanging(value);
					this.SendPropertyChanging();
					this._t_rcon_c = value;
					this.SendPropertyChanged("t_rcon_c");
					this.Ont_rcon_cChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_t_dld1_c", DbType="Int NOT NULL")]
		public int t_dld1_c
		{
			get
			{
				return this._t_dld1_c;
			}
			set
			{
				if ((this._t_dld1_c != value))
				{
					this.Ont_dld1_cChanging(value);
					this.SendPropertyChanging();
					this._t_dld1_c = value;
					this.SendPropertyChanged("t_dld1_c");
					this.Ont_dld1_cChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_t_dld2_c", DbType="Int NOT NULL")]
		public int t_dld2_c
		{
			get
			{
				return this._t_dld2_c;
			}
			set
			{
				if ((this._t_dld2_c != value))
				{
					this.Ont_dld2_cChanging(value);
					this.SendPropertyChanging();
					this._t_dld2_c = value;
					this.SendPropertyChanged("t_dld2_c");
					this.Ont_dld2_cChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_t_Refcntd", DbType="Int NOT NULL")]
		public int t_Refcntd
		{
			get
			{
				return this._t_Refcntd;
			}
			set
			{
				if ((this._t_Refcntd != value))
				{
					this.Ont_RefcntdChanging(value);
					this.SendPropertyChanging();
					this._t_Refcntd = value;
					this.SendPropertyChanged("t_Refcntd");
					this.Ont_RefcntdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_t_Refcntu", DbType="Int NOT NULL")]
		public int t_Refcntu
		{
			get
			{
				return this._t_Refcntu;
			}
			set
			{
				if ((this._t_Refcntu != value))
				{
					this.Ont_RefcntuChanging(value);
					this.SendPropertyChanging();
					this._t_Refcntu = value;
					this.SendPropertyChanged("t_Refcntu");
					this.Ont_RefcntuChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ttdpur040100")]
	public partial class ttdpur040100 : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _t_orno;
		
		private string _t_suno;
		
		private short _t_comp;
		
		private string _t_cotp;
		
		private byte _t_corg;
		
		private string _t_ragr;
		
		private string _t_cpay;
		
		private System.DateTime _t_odat;
		
		private float _t_odis;
		
		private string _t_ccur;
		
		private double _t_ratp;
		
		private int _t_ratf;
		
		private string _t_ccor;
		
		private string _t_cwar;
		
		private int _t_ccon;
		
		private byte _t_cvyn;
		
		private string _t_ccrs;
		
		private string _t_cfrw;
		
		private string _t_cplp;
		
		private string _t_ccty;
		
		private string _t_clan;
		
		private string _t_pspr;
		
		private string _t_pstx;
		
		private string _t_cdec;
		
		private string _t_cfsg;
		
		private System.DateTime _t_ddat;
		
		private System.DateTime _t_ddtc;
		
		private string _t_cbrn;
		
		private string _t_creg;
		
		private string _t_refa;
		
		private string _t_refb;
		
		private int _t_prno;
		
		private string _t_ctrj;
		
		private byte _t_egen;
		
		private int _t_txta;
		
		private int _t_txtb;
		
		private string _t_citt_c;
		
		private byte _t_scon_c;
		
		private byte _t_acon_c;
		
		private byte _t_rcon_c;
		
		private double _t_budi_c;
		
		private float _t_budp_c;
		
		private byte _t_budt_c;
		
		private string _t_budd_c;
		
		private System.DateTime _t_dld1_c;
		
		private System.DateTime _t_dld2_c;
		
		private int _t_Refcntd;
		
		private int _t_Refcntu;
		
    #region Definitionen der Erweiterungsmethoden
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Ont_ornoChanging(int value);
    partial void Ont_ornoChanged();
    partial void Ont_sunoChanging(string value);
    partial void Ont_sunoChanged();
    partial void Ont_compChanging(short value);
    partial void Ont_compChanged();
    partial void Ont_cotpChanging(string value);
    partial void Ont_cotpChanged();
    partial void Ont_corgChanging(byte value);
    partial void Ont_corgChanged();
    partial void Ont_ragrChanging(string value);
    partial void Ont_ragrChanged();
    partial void Ont_cpayChanging(string value);
    partial void Ont_cpayChanged();
    partial void Ont_odatChanging(System.DateTime value);
    partial void Ont_odatChanged();
    partial void Ont_odisChanging(float value);
    partial void Ont_odisChanged();
    partial void Ont_ccurChanging(string value);
    partial void Ont_ccurChanged();
    partial void Ont_ratpChanging(double value);
    partial void Ont_ratpChanged();
    partial void Ont_ratfChanging(int value);
    partial void Ont_ratfChanged();
    partial void Ont_ccorChanging(string value);
    partial void Ont_ccorChanged();
    partial void Ont_cwarChanging(string value);
    partial void Ont_cwarChanged();
    partial void Ont_cconChanging(int value);
    partial void Ont_cconChanged();
    partial void Ont_cvynChanging(byte value);
    partial void Ont_cvynChanged();
    partial void Ont_ccrsChanging(string value);
    partial void Ont_ccrsChanged();
    partial void Ont_cfrwChanging(string value);
    partial void Ont_cfrwChanged();
    partial void Ont_cplpChanging(string value);
    partial void Ont_cplpChanged();
    partial void Ont_cctyChanging(string value);
    partial void Ont_cctyChanged();
    partial void Ont_clanChanging(string value);
    partial void Ont_clanChanged();
    partial void Ont_psprChanging(string value);
    partial void Ont_psprChanged();
    partial void Ont_pstxChanging(string value);
    partial void Ont_pstxChanged();
    partial void Ont_cdecChanging(string value);
    partial void Ont_cdecChanged();
    partial void Ont_cfsgChanging(string value);
    partial void Ont_cfsgChanged();
    partial void Ont_ddatChanging(System.DateTime value);
    partial void Ont_ddatChanged();
    partial void Ont_ddtcChanging(System.DateTime value);
    partial void Ont_ddtcChanged();
    partial void Ont_cbrnChanging(string value);
    partial void Ont_cbrnChanged();
    partial void Ont_cregChanging(string value);
    partial void Ont_cregChanged();
    partial void Ont_refaChanging(string value);
    partial void Ont_refaChanged();
    partial void Ont_refbChanging(string value);
    partial void Ont_refbChanged();
    partial void Ont_prnoChanging(int value);
    partial void Ont_prnoChanged();
    partial void Ont_ctrjChanging(string value);
    partial void Ont_ctrjChanged();
    partial void Ont_egenChanging(byte value);
    partial void Ont_egenChanged();
    partial void Ont_txtaChanging(int value);
    partial void Ont_txtaChanged();
    partial void Ont_txtbChanging(int value);
    partial void Ont_txtbChanged();
    partial void Ont_citt_cChanging(string value);
    partial void Ont_citt_cChanged();
    partial void Ont_scon_cChanging(byte value);
    partial void Ont_scon_cChanged();
    partial void Ont_acon_cChanging(byte value);
    partial void Ont_acon_cChanged();
    partial void Ont_rcon_cChanging(byte value);
    partial void Ont_rcon_cChanged();
    partial void Ont_budi_cChanging(double value);
    partial void Ont_budi_cChanged();
    partial void Ont_budp_cChanging(float value);
    partial void Ont_budp_cChanged();
    partial void Ont_budt_cChanging(byte value);
    partial void Ont_budt_cChanged();
    partial void Ont_budd_cChanging(string value);
    partial void Ont_budd_cChanged();
    partial void Ont_dld1_cChanging(System.DateTime value);
    partial void Ont_dld1_cChanged();
    partial void Ont_dld2_cChanging(System.DateTime value);
    partial void Ont_dld2_cChanged();
    partial void Ont_RefcntdChanging(int value);
    partial void Ont_RefcntdChanged();
    partial void Ont_RefcntuChanging(int value);
    partial void Ont_RefcntuChanged();
    #endregion
		
		public ttdpur040100()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_t_orno", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int t_orno
		{
			get
			{
				return this._t_orno;
			}
			set
			{
				if ((this._t_orno != value))
				{
					this.Ont_ornoChanging(value);
					this.SendPropertyChanging();
					this._t_orno = value;
					this.SendPropertyChanged("t_orno");
					this.Ont_ornoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_t_suno", DbType="VarChar(6) NOT NULL", CanBeNull=false)]
		public string t_suno
		{
			get
			{
				return this._t_suno;
			}
			set
			{
				if ((this._t_suno != value))
				{
					this.Ont_sunoChanging(value);
					this.SendPropertyChanging();
					this._t_suno = value;
					this.SendPropertyChanged("t_suno");
					this.Ont_sunoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_t_comp", DbType="SmallInt NOT NULL")]
		public short t_comp
		{
			get
			{
				return this._t_comp;
			}
			set
			{
				if ((this._t_comp != value))
				{
					this.Ont_compChanging(value);
					this.SendPropertyChanging();
					this._t_comp = value;
					this.SendPropertyChanged("t_comp");
					this.Ont_compChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_t_cotp", DbType="VarChar(3) NOT NULL", CanBeNull=false)]
		public string t_cotp
		{
			get
			{
				return this._t_cotp;
			}
			set
			{
				if ((this._t_cotp != value))
				{
					this.Ont_cotpChanging(value);
					this.SendPropertyChanging();
					this._t_cotp = value;
					this.SendPropertyChanged("t_cotp");
					this.Ont_cotpChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_t_corg", DbType="TinyInt NOT NULL")]
		public byte t_corg
		{
			get
			{
				return this._t_corg;
			}
			set
			{
				if ((this._t_corg != value))
				{
					this.Ont_corgChanging(value);
					this.SendPropertyChanging();
					this._t_corg = value;
					this.SendPropertyChanged("t_corg");
					this.Ont_corgChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_t_ragr", DbType="VarChar(16) NOT NULL", CanBeNull=false)]
		public string t_ragr
		{
			get
			{
				return this._t_ragr;
			}
			set
			{
				if ((this._t_ragr != value))
				{
					this.Ont_ragrChanging(value);
					this.SendPropertyChanging();
					this._t_ragr = value;
					this.SendPropertyChanged("t_ragr");
					this.Ont_ragrChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_t_cpay", DbType="VarChar(3) NOT NULL", CanBeNull=false)]
		public string t_cpay
		{
			get
			{
				return this._t_cpay;
			}
			set
			{
				if ((this._t_cpay != value))
				{
					this.Ont_cpayChanging(value);
					this.SendPropertyChanging();
					this._t_cpay = value;
					this.SendPropertyChanged("t_cpay");
					this.Ont_cpayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_t_odat", DbType="DateTime NOT NULL")]
		public System.DateTime t_odat
		{
			get
			{
				return this._t_odat;
			}
			set
			{
				if ((this._t_odat != value))
				{
					this.Ont_odatChanging(value);
					this.SendPropertyChanging();
					this._t_odat = value;
					this.SendPropertyChanged("t_odat");
					this.Ont_odatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_t_odis", DbType="Real NOT NULL")]
		public float t_odis
		{
			get
			{
				return this._t_odis;
			}
			set
			{
				if ((this._t_odis != value))
				{
					this.Ont_odisChanging(value);
					this.SendPropertyChanging();
					this._t_odis = value;
					this.SendPropertyChanged("t_odis");
					this.Ont_odisChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_t_ccur", DbType="VarChar(3) NOT NULL", CanBeNull=false)]
		public string t_ccur
		{
			get
			{
				return this._t_ccur;
			}
			set
			{
				if ((this._t_ccur != value))
				{
					this.Ont_ccurChanging(value);
					this.SendPropertyChanging();
					this._t_ccur = value;
					this.SendPropertyChanged("t_ccur");
					this.Ont_ccurChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_t_ratp", DbType="Float NOT NULL")]
		public double t_ratp
		{
			get
			{
				return this._t_ratp;
			}
			set
			{
				if ((this._t_ratp != value))
				{
					this.Ont_ratpChanging(value);
					this.SendPropertyChanging();
					this._t_ratp = value;
					this.SendPropertyChanged("t_ratp");
					this.Ont_ratpChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_t_ratf", DbType="Int NOT NULL")]
		public int t_ratf
		{
			get
			{
				return this._t_ratf;
			}
			set
			{
				if ((this._t_ratf != value))
				{
					this.Ont_ratfChanging(value);
					this.SendPropertyChanging();
					this._t_ratf = value;
					this.SendPropertyChanged("t_ratf");
					this.Ont_ratfChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_t_ccor", DbType="VarChar(3) NOT NULL", CanBeNull=false)]
		public string t_ccor
		{
			get
			{
				return this._t_ccor;
			}
			set
			{
				if ((this._t_ccor != value))
				{
					this.Ont_ccorChanging(value);
					this.SendPropertyChanging();
					this._t_ccor = value;
					this.SendPropertyChanged("t_ccor");
					this.Ont_ccorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_t_cwar", DbType="VarChar(3) NOT NULL", CanBeNull=false)]
		public string t_cwar
		{
			get
			{
				return this._t_cwar;
			}
			set
			{
				if ((this._t_cwar != value))
				{
					this.Ont_cwarChanging(value);
					this.SendPropertyChanging();
					this._t_cwar = value;
					this.SendPropertyChanged("t_cwar");
					this.Ont_cwarChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_t_ccon", DbType="Int NOT NULL")]
		public int t_ccon
		{
			get
			{
				return this._t_ccon;
			}
			set
			{
				if ((this._t_ccon != value))
				{
					this.Ont_cconChanging(value);
					this.SendPropertyChanging();
					this._t_ccon = value;
					this.SendPropertyChanged("t_ccon");
					this.Ont_cconChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_t_cvyn", DbType="TinyInt NOT NULL")]
		public byte t_cvyn
		{
			get
			{
				return this._t_cvyn;
			}
			set
			{
				if ((this._t_cvyn != value))
				{
					this.Ont_cvynChanging(value);
					this.SendPropertyChanging();
					this._t_cvyn = value;
					this.SendPropertyChanged("t_cvyn");
					this.Ont_cvynChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_t_ccrs", DbType="VarChar(3) NOT NULL", CanBeNull=false)]
		public string t_ccrs
		{
			get
			{
				return this._t_ccrs;
			}
			set
			{
				if ((this._t_ccrs != value))
				{
					this.Ont_ccrsChanging(value);
					this.SendPropertyChanging();
					this._t_ccrs = value;
					this.SendPropertyChanged("t_ccrs");
					this.Ont_ccrsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_t_cfrw", DbType="VarChar(3) NOT NULL", CanBeNull=false)]
		public string t_cfrw
		{
			get
			{
				return this._t_cfrw;
			}
			set
			{
				if ((this._t_cfrw != value))
				{
					this.Ont_cfrwChanging(value);
					this.SendPropertyChanging();
					this._t_cfrw = value;
					this.SendPropertyChanged("t_cfrw");
					this.Ont_cfrwChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_t_cplp", DbType="VarChar(3) NOT NULL", CanBeNull=false)]
		public string t_cplp
		{
			get
			{
				return this._t_cplp;
			}
			set
			{
				if ((this._t_cplp != value))
				{
					this.Ont_cplpChanging(value);
					this.SendPropertyChanging();
					this._t_cplp = value;
					this.SendPropertyChanged("t_cplp");
					this.Ont_cplpChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_t_ccty", DbType="VarChar(3) NOT NULL", CanBeNull=false)]
		public string t_ccty
		{
			get
			{
				return this._t_ccty;
			}
			set
			{
				if ((this._t_ccty != value))
				{
					this.Ont_cctyChanging(value);
					this.SendPropertyChanging();
					this._t_ccty = value;
					this.SendPropertyChanged("t_ccty");
					this.Ont_cctyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_t_clan", DbType="VarChar(3) NOT NULL", CanBeNull=false)]
		public string t_clan
		{
			get
			{
				return this._t_clan;
			}
			set
			{
				if ((this._t_clan != value))
				{
					this.Ont_clanChanging(value);
					this.SendPropertyChanging();
					this._t_clan = value;
					this.SendPropertyChanged("t_clan");
					this.Ont_clanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_t_pspr", DbType="VarChar(6) NOT NULL", CanBeNull=false)]
		public string t_pspr
		{
			get
			{
				return this._t_pspr;
			}
			set
			{
				if ((this._t_pspr != value))
				{
					this.Ont_psprChanging(value);
					this.SendPropertyChanging();
					this._t_pspr = value;
					this.SendPropertyChanged("t_pspr");
					this.Ont_psprChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_t_pstx", DbType="VarChar(6) NOT NULL", CanBeNull=false)]
		public string t_pstx
		{
			get
			{
				return this._t_pstx;
			}
			set
			{
				if ((this._t_pstx != value))
				{
					this.Ont_pstxChanging(value);
					this.SendPropertyChanging();
					this._t_pstx = value;
					this.SendPropertyChanged("t_pstx");
					this.Ont_pstxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_t_cdec", DbType="VarChar(3) NOT NULL", CanBeNull=false)]
		public string t_cdec
		{
			get
			{
				return this._t_cdec;
			}
			set
			{
				if ((this._t_cdec != value))
				{
					this.Ont_cdecChanging(value);
					this.SendPropertyChanging();
					this._t_cdec = value;
					this.SendPropertyChanged("t_cdec");
					this.Ont_cdecChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_t_cfsg", DbType="VarChar(3) NOT NULL", CanBeNull=false)]
		public string t_cfsg
		{
			get
			{
				return this._t_cfsg;
			}
			set
			{
				if ((this._t_cfsg != value))
				{
					this.Ont_cfsgChanging(value);
					this.SendPropertyChanging();
					this._t_cfsg = value;
					this.SendPropertyChanged("t_cfsg");
					this.Ont_cfsgChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_t_ddat", DbType="DateTime NOT NULL")]
		public System.DateTime t_ddat
		{
			get
			{
				return this._t_ddat;
			}
			set
			{
				if ((this._t_ddat != value))
				{
					this.Ont_ddatChanging(value);
					this.SendPropertyChanging();
					this._t_ddat = value;
					this.SendPropertyChanged("t_ddat");
					this.Ont_ddatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_t_ddtc", DbType="DateTime NOT NULL")]
		public System.DateTime t_ddtc
		{
			get
			{
				return this._t_ddtc;
			}
			set
			{
				if ((this._t_ddtc != value))
				{
					this.Ont_ddtcChanging(value);
					this.SendPropertyChanging();
					this._t_ddtc = value;
					this.SendPropertyChanged("t_ddtc");
					this.Ont_ddtcChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_t_cbrn", DbType="VarChar(6) NOT NULL", CanBeNull=false)]
		public string t_cbrn
		{
			get
			{
				return this._t_cbrn;
			}
			set
			{
				if ((this._t_cbrn != value))
				{
					this.Ont_cbrnChanging(value);
					this.SendPropertyChanging();
					this._t_cbrn = value;
					this.SendPropertyChanged("t_cbrn");
					this.Ont_cbrnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_t_creg", DbType="VarChar(3) NOT NULL", CanBeNull=false)]
		public string t_creg
		{
			get
			{
				return this._t_creg;
			}
			set
			{
				if ((this._t_creg != value))
				{
					this.Ont_cregChanging(value);
					this.SendPropertyChanging();
					this._t_creg = value;
					this.SendPropertyChanged("t_creg");
					this.Ont_cregChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_t_refa", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string t_refa
		{
			get
			{
				return this._t_refa;
			}
			set
			{
				if ((this._t_refa != value))
				{
					this.Ont_refaChanging(value);
					this.SendPropertyChanging();
					this._t_refa = value;
					this.SendPropertyChanged("t_refa");
					this.Ont_refaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_t_refb", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string t_refb
		{
			get
			{
				return this._t_refb;
			}
			set
			{
				if ((this._t_refb != value))
				{
					this.Ont_refbChanging(value);
					this.SendPropertyChanging();
					this._t_refb = value;
					this.SendPropertyChanged("t_refb");
					this.Ont_refbChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_t_prno", DbType="Int NOT NULL")]
		public int t_prno
		{
			get
			{
				return this._t_prno;
			}
			set
			{
				if ((this._t_prno != value))
				{
					this.Ont_prnoChanging(value);
					this.SendPropertyChanging();
					this._t_prno = value;
					this.SendPropertyChanged("t_prno");
					this.Ont_prnoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_t_ctrj", DbType="VarChar(3) NOT NULL", CanBeNull=false)]
		public string t_ctrj
		{
			get
			{
				return this._t_ctrj;
			}
			set
			{
				if ((this._t_ctrj != value))
				{
					this.Ont_ctrjChanging(value);
					this.SendPropertyChanging();
					this._t_ctrj = value;
					this.SendPropertyChanged("t_ctrj");
					this.Ont_ctrjChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_t_egen", DbType="TinyInt NOT NULL")]
		public byte t_egen
		{
			get
			{
				return this._t_egen;
			}
			set
			{
				if ((this._t_egen != value))
				{
					this.Ont_egenChanging(value);
					this.SendPropertyChanging();
					this._t_egen = value;
					this.SendPropertyChanged("t_egen");
					this.Ont_egenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_t_txta", DbType="Int NOT NULL")]
		public int t_txta
		{
			get
			{
				return this._t_txta;
			}
			set
			{
				if ((this._t_txta != value))
				{
					this.Ont_txtaChanging(value);
					this.SendPropertyChanging();
					this._t_txta = value;
					this.SendPropertyChanged("t_txta");
					this.Ont_txtaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_t_txtb", DbType="Int NOT NULL")]
		public int t_txtb
		{
			get
			{
				return this._t_txtb;
			}
			set
			{
				if ((this._t_txtb != value))
				{
					this.Ont_txtbChanging(value);
					this.SendPropertyChanging();
					this._t_txtb = value;
					this.SendPropertyChanged("t_txtb");
					this.Ont_txtbChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_t_citt_c", DbType="VarChar(3) NOT NULL", CanBeNull=false)]
		public string t_citt_c
		{
			get
			{
				return this._t_citt_c;
			}
			set
			{
				if ((this._t_citt_c != value))
				{
					this.Ont_citt_cChanging(value);
					this.SendPropertyChanging();
					this._t_citt_c = value;
					this.SendPropertyChanged("t_citt_c");
					this.Ont_citt_cChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_t_scon_c", DbType="TinyInt NOT NULL")]
		public byte t_scon_c
		{
			get
			{
				return this._t_scon_c;
			}
			set
			{
				if ((this._t_scon_c != value))
				{
					this.Ont_scon_cChanging(value);
					this.SendPropertyChanging();
					this._t_scon_c = value;
					this.SendPropertyChanged("t_scon_c");
					this.Ont_scon_cChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_t_acon_c", DbType="TinyInt NOT NULL")]
		public byte t_acon_c
		{
			get
			{
				return this._t_acon_c;
			}
			set
			{
				if ((this._t_acon_c != value))
				{
					this.Ont_acon_cChanging(value);
					this.SendPropertyChanging();
					this._t_acon_c = value;
					this.SendPropertyChanged("t_acon_c");
					this.Ont_acon_cChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_t_rcon_c", DbType="TinyInt NOT NULL")]
		public byte t_rcon_c
		{
			get
			{
				return this._t_rcon_c;
			}
			set
			{
				if ((this._t_rcon_c != value))
				{
					this.Ont_rcon_cChanging(value);
					this.SendPropertyChanging();
					this._t_rcon_c = value;
					this.SendPropertyChanged("t_rcon_c");
					this.Ont_rcon_cChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_t_budi_c", DbType="Float NOT NULL")]
		public double t_budi_c
		{
			get
			{
				return this._t_budi_c;
			}
			set
			{
				if ((this._t_budi_c != value))
				{
					this.Ont_budi_cChanging(value);
					this.SendPropertyChanging();
					this._t_budi_c = value;
					this.SendPropertyChanged("t_budi_c");
					this.Ont_budi_cChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_t_budp_c", DbType="Real NOT NULL")]
		public float t_budp_c
		{
			get
			{
				return this._t_budp_c;
			}
			set
			{
				if ((this._t_budp_c != value))
				{
					this.Ont_budp_cChanging(value);
					this.SendPropertyChanging();
					this._t_budp_c = value;
					this.SendPropertyChanged("t_budp_c");
					this.Ont_budp_cChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_t_budt_c", DbType="TinyInt NOT NULL")]
		public byte t_budt_c
		{
			get
			{
				return this._t_budt_c;
			}
			set
			{
				if ((this._t_budt_c != value))
				{
					this.Ont_budt_cChanging(value);
					this.SendPropertyChanging();
					this._t_budt_c = value;
					this.SendPropertyChanged("t_budt_c");
					this.Ont_budt_cChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_t_budd_c", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string t_budd_c
		{
			get
			{
				return this._t_budd_c;
			}
			set
			{
				if ((this._t_budd_c != value))
				{
					this.Ont_budd_cChanging(value);
					this.SendPropertyChanging();
					this._t_budd_c = value;
					this.SendPropertyChanged("t_budd_c");
					this.Ont_budd_cChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_t_dld1_c", DbType="DateTime NOT NULL")]
		public System.DateTime t_dld1_c
		{
			get
			{
				return this._t_dld1_c;
			}
			set
			{
				if ((this._t_dld1_c != value))
				{
					this.Ont_dld1_cChanging(value);
					this.SendPropertyChanging();
					this._t_dld1_c = value;
					this.SendPropertyChanged("t_dld1_c");
					this.Ont_dld1_cChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_t_dld2_c", DbType="DateTime NOT NULL")]
		public System.DateTime t_dld2_c
		{
			get
			{
				return this._t_dld2_c;
			}
			set
			{
				if ((this._t_dld2_c != value))
				{
					this.Ont_dld2_cChanging(value);
					this.SendPropertyChanging();
					this._t_dld2_c = value;
					this.SendPropertyChanged("t_dld2_c");
					this.Ont_dld2_cChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_t_Refcntd", DbType="Int NOT NULL")]
		public int t_Refcntd
		{
			get
			{
				return this._t_Refcntd;
			}
			set
			{
				if ((this._t_Refcntd != value))
				{
					this.Ont_RefcntdChanging(value);
					this.SendPropertyChanging();
					this._t_Refcntd = value;
					this.SendPropertyChanged("t_Refcntd");
					this.Ont_RefcntdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_t_Refcntu", DbType="Int NOT NULL")]
		public int t_Refcntu
		{
			get
			{
				return this._t_Refcntu;
			}
			set
			{
				if ((this._t_Refcntu != value))
				{
					this.Ont_RefcntuChanging(value);
					this.SendPropertyChanging();
					this._t_Refcntu = value;
					this.SendPropertyChanged("t_Refcntu");
					this.Ont_RefcntuChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
