<?xml version="1.0" encoding="utf-8"?><Database Name="baan4db" Class="Baan4DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=baan4;Initial Catalog=baan4db;Integrated Security=True" SettingsObjectName="ORDesignerWalktrough.Properties.Settings" SettingsPropertyName="baan4dbConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.ttccom020100" Member="ttccom020100">
    <Type Name="ttccom020100">
      <Column Name="t_suno" Type="System.String" DbType="VarChar(6) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="t_ctit" Type="System.String" DbType="VarChar(3) NOT NULL" CanBeNull="false" />
      <Column Name="t_nama" Type="System.String" DbType="VarChar(35) NOT NULL" CanBeNull="false" />
      <Column Name="t_namb" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="t_namc" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="t_namd" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="t_name" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="t_namf" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="t_pstc" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="t_comp" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="t_creg" Type="System.String" DbType="VarChar(3) NOT NULL" CanBeNull="false" />
      <Column Name="t_pspr" Type="System.String" DbType="VarChar(6) NOT NULL" CanBeNull="false" />
      <Column Name="t_pstx" Type="System.String" DbType="VarChar(6) NOT NULL" CanBeNull="false" />
      <Column Name="t_sndr" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="t_ccor" Type="System.String" DbType="VarChar(3) NOT NULL" CanBeNull="false" />
      <Column Name="t_cwar" Type="System.String" DbType="VarChar(3) NOT NULL" CanBeNull="false" />
      <Column Name="t_refa" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="t_refs" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="t_ocus" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="t_telp" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="t_telx" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="t_tefx" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="t_seak" Type="System.String" DbType="VarChar(16) NOT NULL" CanBeNull="false" />
      <Column Name="t_cbrn" Type="System.String" DbType="VarChar(6) NOT NULL" CanBeNull="false" />
      <Column Name="t_cban" Type="System.String" DbType="VarChar(3) NOT NULL" CanBeNull="false" />
      <Column Name="t_cfcc" Type="System.String" DbType="VarChar(3) NOT NULL" CanBeNull="false" />
      <Column Name="t_fano" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="t_ccon" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="t_cpay" Type="System.String" DbType="VarChar(3) NOT NULL" CanBeNull="false" />
      <Column Name="t_ccrs" Type="System.String" DbType="VarChar(3) NOT NULL" CanBeNull="false" />
      <Column Name="t_cdec" Type="System.String" DbType="VarChar(3) NOT NULL" CanBeNull="false" />
      <Column Name="t_ccty" Type="System.String" DbType="VarChar(3) NOT NULL" CanBeNull="false" />
      <Column Name="t_clan" Type="System.String" DbType="VarChar(3) NOT NULL" CanBeNull="false" />
      <Column Name="t_ccur" Type="System.String" DbType="VarChar(3) NOT NULL" CanBeNull="false" />
      <Column Name="t_cvyn" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="t_scus" Type="System.String" DbType="VarChar(6) NOT NULL" CanBeNull="false" />
      <Column Name="t_cplp" Type="System.String" DbType="VarChar(3) NOT NULL" CanBeNull="false" />
      <Column Name="t_cfsg" Type="System.String" DbType="VarChar(3) NOT NULL" CanBeNull="false" />
      <Column Name="t_paym" Type="System.String" DbType="VarChar(3) NOT NULL" CanBeNull="false" />
      <Column Name="t_cuno" Type="System.String" DbType="VarChar(6) NOT NULL" CanBeNull="false" />
      <Column Name="t_qual" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="t_buor" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="t_buin" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="t_odis" Type="System.Single" DbType="Real NOT NULL" CanBeNull="false" />
      <Column Name="t_subc" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="t_cryr" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="t_tovr_1" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="t_tovr_2" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="t_tovr_3" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="t_tovr_4" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="t_tovr_5" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="t_sust" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="t_eded" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="t_cadr" Type="System.String" DbType="VarChar(6) NOT NULL" CanBeNull="false" />
      <Column Name="t_fovn" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="t_inrl" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="t_iscn" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="t_cotp" Type="System.String" DbType="VarChar(3) NOT NULL" CanBeNull="false" />
      <Column Name="t_txta" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="t_geoc_l" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="t_scon_c" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="t_rcon_c" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="t_dld1_c" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="t_dld2_c" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="t_Refcntd" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="t_Refcntu" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.ttdpur040100" Member="ttdpur040100">
    <Type Name="ttdpur040100">
      <Column Name="t_orno" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="t_suno" Type="System.String" DbType="VarChar(6) NOT NULL" CanBeNull="false" />
      <Column Name="t_comp" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="t_cotp" Type="System.String" DbType="VarChar(3) NOT NULL" CanBeNull="false" />
      <Column Name="t_corg" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="t_ragr" Type="System.String" DbType="VarChar(16) NOT NULL" CanBeNull="false" />
      <Column Name="t_cpay" Type="System.String" DbType="VarChar(3) NOT NULL" CanBeNull="false" />
      <Column Name="t_odat" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="t_odis" Type="System.Single" DbType="Real NOT NULL" CanBeNull="false" />
      <Column Name="t_ccur" Type="System.String" DbType="VarChar(3) NOT NULL" CanBeNull="false" />
      <Column Name="t_ratp" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="t_ratf" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="t_ccor" Type="System.String" DbType="VarChar(3) NOT NULL" CanBeNull="false" />
      <Column Name="t_cwar" Type="System.String" DbType="VarChar(3) NOT NULL" CanBeNull="false" />
      <Column Name="t_ccon" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="t_cvyn" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="t_ccrs" Type="System.String" DbType="VarChar(3) NOT NULL" CanBeNull="false" />
      <Column Name="t_cfrw" Type="System.String" DbType="VarChar(3) NOT NULL" CanBeNull="false" />
      <Column Name="t_cplp" Type="System.String" DbType="VarChar(3) NOT NULL" CanBeNull="false" />
      <Column Name="t_ccty" Type="System.String" DbType="VarChar(3) NOT NULL" CanBeNull="false" />
      <Column Name="t_clan" Type="System.String" DbType="VarChar(3) NOT NULL" CanBeNull="false" />
      <Column Name="t_pspr" Type="System.String" DbType="VarChar(6) NOT NULL" CanBeNull="false" />
      <Column Name="t_pstx" Type="System.String" DbType="VarChar(6) NOT NULL" CanBeNull="false" />
      <Column Name="t_cdec" Type="System.String" DbType="VarChar(3) NOT NULL" CanBeNull="false" />
      <Column Name="t_cfsg" Type="System.String" DbType="VarChar(3) NOT NULL" CanBeNull="false" />
      <Column Name="t_ddat" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="t_ddtc" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="t_cbrn" Type="System.String" DbType="VarChar(6) NOT NULL" CanBeNull="false" />
      <Column Name="t_creg" Type="System.String" DbType="VarChar(3) NOT NULL" CanBeNull="false" />
      <Column Name="t_refa" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="t_refb" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="t_prno" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="t_ctrj" Type="System.String" DbType="VarChar(3) NOT NULL" CanBeNull="false" />
      <Column Name="t_egen" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="t_txta" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="t_txtb" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="t_citt_c" Type="System.String" DbType="VarChar(3) NOT NULL" CanBeNull="false" />
      <Column Name="t_scon_c" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="t_acon_c" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="t_rcon_c" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="t_budi_c" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="t_budp_c" Type="System.Single" DbType="Real NOT NULL" CanBeNull="false" />
      <Column Name="t_budt_c" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="t_budd_c" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="t_dld1_c" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="t_dld2_c" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="t_Refcntd" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="t_Refcntu" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>